
let users= [{"id":1,"name":"Wiley","email":"wanelay0@dailymail.co.uk","gender":"Male"},
{"id":2,"name":"Barney","email":"bbodd1@discuz.net","gender":"Male"},
{"id":3,"name":"Tremaine","email":"tguiraud2@slideshare.net","gender":"Male"},
{"id":4,"name":"Sara-ann","email":"slourenco3@smh.com.au","gender":"Agender"},
{"id":5,"name":"Patton","email":"pvassel4@wp.com","gender":"Male"},
{"id":6,"name":"Renado","email":"rotowey5@nasa.gov","gender":"Male"},
{"id":7,"name":"Onofredo","email":"overecker6@icq.com","gender":"Male"},
{"id":8,"name":"Teodorico","email":"tgrovier7@ow.ly","gender":"Male"},
{"id":9,"name":"Donella","email":"dbraunthal8@nbcnews.com","gender":"Genderqueer"},
{"id":10,"name":"Adriane","email":"apeskett9@marketwatch.com","gender":"Female"},
{"id":11,"name":"Felipa","email":"facostaa@seesaa.net","gender":"Female"},
{"id":12,"name":"Arvie","email":"asymsonb@symantec.com","gender":"Polygender"},
{"id":13,"name":"Sonny","email":"scordonc@sourceforge.net","gender":"Female"},
{"id":14,"name":"Naomi","email":"nheatond@umich.edu","gender":"Female"},
{"id":15,"name":"Richmound","email":"rrewane@gov.uk","gender":"Male"},
{"id":16,"name":"Erskine","email":"eghidellif@wikimedia.org","gender":"Male"},
{"id":17,"name":"Vassily","email":"vbeeverg@about.com","gender":"Male"},
{"id":18,"name":"Chelsie","email":"cmclaughlanh@rambler.ru","gender":"Female"},
{"id":19,"name":"Ellwood","email":"evedenisovi@cloudflare.com","gender":"Male"},
{"id":20,"name":"Johnnie","email":"jbuggej@etsy.com","gender":"Male"},
{"id":21,"name":"Lewie","email":"lyarmouthk@kickstarter.com","gender":"Male"},
{"id":22,"name":"Damon","email":"dloeberl@t-online.de","gender":"Male"},
{"id":23,"name":"Zach","email":"zgalileem@umn.edu","gender":"Male"},
{"id":24,"name":"Inger","email":"ihoffnern@vk.com","gender":"Male"},
{"id":25,"name":"Starlene","email":"sjolyo@vk.com","gender":"Female"},
{"id":26,"name":"Connie","email":"cbroomfieldp@spotify.com","gender":"Female"},
{"id":27,"name":"Katlin","email":"ksineq@comcast.net","gender":"Female"},
{"id":28,"name":"Susie","email":"schesselr@google.com.hk","gender":"Female"},
{"id":29,"name":"Teri","email":"tbiless@cloudflare.com","gender":"Female"},
{"id":30,"name":"Rodie","email":"rfairbrothert@biglobe.ne.jp","gender":"Female"},
{"id":31,"name":"Calley","email":"cbaggeu@vistaprint.com","gender":"Female"},
{"id":32,"name":"Ambrose","email":"ayushkovv@is.gd","gender":"Male"},
{"id":33,"name":"Bruce","email":"bbeavenw@redcross.org","gender":"Male"},
{"id":34,"name":"Cassandry","email":"csafflex@bandcamp.com","gender":"Female"},
{"id":35,"name":"Justinn","email":"jwelberryy@123-reg.co.uk","gender":"Non-binary"},
{"id":36,"name":"Bertrando","email":"bleamingz@stumbleupon.com","gender":"Male"},
{"id":37,"name":"Jaquith","email":"jleggate10@zdnet.com","gender":"Female"},
{"id":38,"name":"Cleveland","email":"cmcmullen11@slashdot.org","gender":"Genderfluid"},
{"id":39,"name":"Brnaba","email":"bbaselli12@exblog.jp","gender":"Male"},
{"id":40,"name":"Sheffie","email":"srault13@biblegateway.com","gender":"Genderfluid"},
{"id":41,"name":"Rolf","email":"rtullis14@sciencedaily.com","gender":"Agender"},
{"id":42,"name":"Aili","email":"abraisted15@wikispaces.com","gender":"Female"},
{"id":43,"name":"Farris","email":"fskerratt16@upenn.edu","gender":"Male"},
{"id":44,"name":"Diego","email":"dhufton17@about.me","gender":"Male"},
{"id":45,"name":"Shandee","email":"sshelmardine18@topsy.com","gender":"Female"},
{"id":46,"name":"Mattie","email":"mcassy19@apple.com","gender":"Female"},
{"id":47,"name":"Clovis","email":"cbontine1a@oaic.gov.au","gender":"Female"},
{"id":48,"name":"Carolee","email":"ckilgrove1b@squidoo.com","gender":"Female"},
{"id":49,"name":"Cyrille","email":"ceddington1c@blogspot.com","gender":"Male"},
{"id":50,"name":"Carilyn","email":"cfazan1d@i2i.jp","gender":"Female"},
{"id":51,"name":"Turner","email":"tronca1e@shareasale.com","gender":"Male"},
{"id":52,"name":"Guillermo","email":"gcowherd1f@github.io","gender":"Male"},
{"id":53,"name":"Griselda","email":"gprimak1g@51.la","gender":"Female"},
{"id":54,"name":"Yetta","email":"yhakes1h@tamu.edu","gender":"Female"},
{"id":55,"name":"Margareta","email":"mbarclay1i@discuz.net","gender":"Female"},
{"id":56,"name":"Viviene","email":"vswettenham1j@naver.com","gender":"Female"},
{"id":57,"name":"Levon","email":"lmacmenamin1k@time.com","gender":"Male"},
{"id":58,"name":"Mela","email":"mcatterick1l@gov.uk","gender":"Female"},
{"id":59,"name":"Dorita","email":"dtattersdill1m@bizjournals.com","gender":"Genderqueer"},
{"id":60,"name":"Riordan","email":"rdenekamp1n@cpanel.net","gender":"Male"},
{"id":61,"name":"Alexis","email":"abarnet1o@buzzfeed.com","gender":"Male"},
{"id":62,"name":"Eleanor","email":"emessruther1p@ucla.edu","gender":"Female"},
{"id":63,"name":"Ellen","email":"ewickenden1q@cam.ac.uk","gender":"Female"},
{"id":64,"name":"Norton","email":"nload1r@loc.gov","gender":"Male"},
{"id":65,"name":"Husain","email":"hlandsman1s@prnewswire.com","gender":"Genderqueer"},
{"id":66,"name":"Natale","email":"ndubock1t@jalbum.net","gender":"Male"},
{"id":67,"name":"Travus","email":"tboshere1u@g.co","gender":"Male"},
{"id":68,"name":"Gwenny","email":"gdignam1v@timesonline.co.uk","gender":"Female"},
{"id":69,"name":"Alexander","email":"alathan1w@ovh.net","gender":"Male"},
{"id":70,"name":"Emelda","email":"etaggerty1x@altervista.org","gender":"Female"},
{"id":71,"name":"Ivory","email":"iurrey1y@google.co.uk","gender":"Female"},
{"id":72,"name":"Marcello","email":"mjackett1z@mysql.com","gender":"Male"},
{"id":73,"name":"Dennie","email":"ddunne20@dagondesign.com","gender":"Male"},
{"id":74,"name":"Wittie","email":"wpessler21@odnoklassniki.ru","gender":"Polygender"},
{"id":75,"name":"Nonna","email":"nswitzer22@reuters.com","gender":"Female"},
{"id":76,"name":"Nicolas","email":"nporker23@wikipedia.org","gender":"Agender"},
{"id":77,"name":"Dionne","email":"dtolputt24@cnet.com","gender":"Female"},
{"id":78,"name":"Roddie","email":"rdepka25@hibu.com","gender":"Male"},
{"id":79,"name":"Min","email":"mrussen26@who.int","gender":"Female"},
{"id":80,"name":"Paulina","email":"phawthorn27@weibo.com","gender":"Female"},
{"id":81,"name":"Darlene","email":"deickhoff28@blinklist.com","gender":"Genderfluid"},
{"id":82,"name":"Brad","email":"blampaert29@hud.gov","gender":"Male"},
{"id":83,"name":"Mitzi","email":"mwisam2a@ucoz.ru","gender":"Female"},
{"id":84,"name":"Gayleen","email":"gakers2b@booking.com","gender":"Female"},
{"id":85,"name":"Vail","email":"vgosson2c@bloomberg.com","gender":"Male"},
{"id":86,"name":"Ernie","email":"eobrian2d@is.gd","gender":"Male"},
{"id":87,"name":"Howey","email":"hbottrill2e@fda.gov","gender":"Male"},
{"id":88,"name":"Luis","email":"lhapps2f@kickstarter.com","gender":"Male"},
{"id":89,"name":"Edvard","email":"ewatkiss2g@cyberchimps.com","gender":"Male"},
{"id":90,"name":"Dido","email":"dskynner2h@shutterfly.com","gender":"Female"},
{"id":91,"name":"Kayne","email":"kfaltin2i@photobucket.com","gender":"Male"},
{"id":92,"name":"Cly","email":"cblainey2j@sciencedaily.com","gender":"Male"},
{"id":93,"name":"Reeva","email":"rratnage2k@discovery.com","gender":"Female"},
{"id":94,"name":"Gwenny","email":"gmcavin2l@technorati.com","gender":"Female"},
{"id":95,"name":"Agneta","email":"ahyam2m@europa.eu","gender":"Female"},
{"id":96,"name":"Jaymie","email":"jstolting2n@about.com","gender":"Male"},
{"id":97,"name":"Andres","email":"abartalin2o@bigcartel.com","gender":"Male"},
{"id":98,"name":"Janos","email":"jpionter2p@washingtonpost.com","gender":"Male"},
{"id":99,"name":"Amanda","email":"aemmison2q@cloudflare.com","gender":"Female"},
{"id":100,"name":"Bobbie","email":"bthreadgould2r@sciencedaily.com","gender":"Bigender"}]


var mCount=0
var fCount=0
for( user of users){
    if(user.gender =="Male"){
        mCount++
    }
    else{
        fCount++
    }
}
console.log("No of Male Users: ", mCount)
console.log("No of FeMale Users: ", fCount)

console.log(users.length)